/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.centralleitos.ui;


import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import br.newtonpaiva.centralleitos.modelos.Unidade;
import br.newtonpaiva.centralleitos.modelos.AutenticConfig;
import br.newtonpaiva.centralleitos.modelos.ConectaBanco;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import java.util.Random;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 12104050
 */
public class TelaCadastroUnidade extends javax.swing.JDialog {
    
    private final EntityManager em;
    
    private Integer idUnidade;

    /**
     * Creates new form TelaCadastroUnidade
     */
    public TelaCadastroUnidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        em = Persistence
                .createEntityManagerFactory("CentralLeitosPU")
                .createEntityManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUf = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Unidade");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel7.setText("UF:");

        jLabel8.setText("Telefone:");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel1.setText("CADASTRO HOSPITAL");

        jLabel3.setText("CEP:");

        jLabel4.setText("Rua:");

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Nº:");

        jLabel6.setText("Cidade:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCepFocusLost(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Bairro:");

        txtUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecionar>", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        txtUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLimpar)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel6)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        em.getTransaction().begin();
        
        Unidade u;
        if(this.idUnidade == null){
            u = new Unidade();
            em.persist(u);
            
        } else {
            u = em.find(Unidade.class, idUnidade);
            em.merge(u);
        }
        
        UUID codAut = UUID.randomUUID();
        
         try{
            
        // Cria arquivo
        File file = new File("configAut.txt");
        
        // Se o arquivo nao existir, ele gera
        if (!file.exists()) {
                file.createNewFile();
            }
      
                
        // Prepara para escrever no arquivo
        FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            
        // Escreve e fecha arquivo
        bw.write(String.valueOf(codAut));
            bw.close();
            
             System.out.println("Feito =D");
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
        u.setNome(txtNome.getText());
        u.setCep(txtCep.getText());
        u.setEndereco(txtRua.getText());
        u.setNumero(txtNumero.getText());
        u.setCidade(txtCidade.getText());
        u.setUf(txtUf.getSelectedItem().toString());
        u.setTelefone(txtTelefone.getText());
        u.setAutCod(codAut.toString());
        
        
        
    //      u.setEmail(txtEmail.getText());
    //      u.setSenha(txtSenha.getText());
        
        
        /*em.getTransaction().commit();
        JOptionPane
                .showMessageDialog(this,"Unidade cadastrada com sucesso!");
        */
        btnLimpar.doClick();
        
        
        
       

    
   
    try{
     // Le o arquivo
            FileReader ler = new FileReader("configAut.txt");
            BufferedReader reader = new BufferedReader(ler);  
            String cod;
            while( (cod = reader.readLine()) != null ){
                System.out.println("esse e o codigo do arquivo txt: " + cod);
                
            }
            
            
            ConectaBanco con = new ConectaBanco();
            con.conectar();
            Statement st = con.con.createStatement();
            
            st.executeQuery("Select AUTCOD from unidade");
            
            ResultSet rs = st.getResultSet();
            while (rs.next()){
                //JOptionPane.showMessageDialog(this,rs.getString("COD"));
                JOptionPane.showMessageDialog(this,rs.getString("AUTCOD"));
            }
            
                    
    }
     
    catch (IOException e) {
            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroUnidade.class.getName()).log(Level.SEVERE, null, ex);
        }
    finally{
        em.getTransaction().commit();
        JOptionPane
                .showMessageDialog(this,"Unidade cadastrada com sucesso!");
    }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtNome.setText("");
        txtCep.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtUf.setSelectedIndex(0);
        txtTelefone.setText("");

        
        
        txtNome.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCepFocusLost
        // TODO add your handling code here:
         ViaCEP viaCep = new ViaCEP();

        String cp = txtCep.getText().replace("-","");

        try {
            viaCep.buscar(cp);
            txtRua.setText(viaCep.getLogradouro());
            txtBairro.setText(viaCep.getBairro());
            txtCidade.setText(viaCep.getLocalidade());
            //txtUf.setText(viaCep.getUf());
            
            switch(viaCep.getUf()){
                case "AC":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(1);
                    break;
                case "AL":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(2);
                    break;
                case "AP":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(3);
                    break;
                case "AM":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(4);
                    break;
                case "BA":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(5);
                    break;
                case "CE":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(6);
                    break;
                case "DF":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(7);
                    break;
                case "ES":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(8);
                    break;
                case "GO":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(9);
                    break;
                case "MA":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(10);
                    break;
                case "MT":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(11);
                    break;
                case "MS":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(12);
                    break;
                case "MG":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(13);
                    break;
                case "PA":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(14);
                    break;
                case "PB":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(15);
                    break;
                case "PR":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(16);
                    break;
                case "PE":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(17);
                    break;
                case "PI":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(18);
                    break;
                case "RJ":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(19);
                    break;
                case "RN":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(20);
                    break;
                case "RS":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(21);
                    break;
                case "RO":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(22);
                    break;
                case "RR":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(23);
                    break;
                case "SC":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(24);
                    break;
                case "SP":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(25);
                    break;
                case "SE":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(26);
                    break;
                case "TO":
                    txtUf.setEnabled(false);
                    txtRua.setEditable(false);
                    txtBairro.setEditable(false);
                    txtCidade.setEditable(false);
                    txtUf.setSelectedIndex(27);
                    break;
                default:
                    txtUf.setEnabled(true);
                    txtUf.setSelectedIndex(0);
            }
            
        } catch (ViaCEPException ex) {
            JOptionPane.showMessageDialog(null, "Falha ao Buscar o CEP, preencha manualmente","AVISO!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCepFocusLost

    private void txtUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUfActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new MenuInicial().setVisible(true);
    }//GEN-LAST:event_formWindowClosed
       
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroUnidade dialog = new TelaCadastroUnidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JComboBox txtUf;
    // End of variables declaration//GEN-END:variables
}
