/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.centralleitos.ui;

import br.newtonpaiva.centralleitos.ui.MenuInicial;
import br.newtonpaiva.centralleitos.modelos.Unidade;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Kaique
 */
public class TelaTabelaUnidade extends javax.swing.JDialog {

    private EntityManager em;
    
    private Integer idUnidade;

 
    
    /**
     * Creates new form TelaTabelaUnidade
     */
    public TelaTabelaUnidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        em = Persistence
                .createEntityManagerFactory("CentralLeitosPU")
                .createEntityManager();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnidade = new javax.swing.JTable();
        BtnCadastroUnidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unidades");

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblUnidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CEP", "Endereço", "Nº", "Cidade", "UF", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUnidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUnidade);

        BtnCadastroUnidade.setText("Cadastrar unidade");
        BtnCadastroUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroUnidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCadastroUnidade)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnCadastroUnidade)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int row = tblUnidade.getSelectedRow();

        if(row == -1){
            JOptionPane.showMessageDialog(this, "Favor selecionar uma unidade.");
        } else {
            Integer id = (Integer) tblUnidade.getModel().getValueAt(row, 0);

            Unidade u = em.find(Unidade.class, id);
            em.getTransaction().begin();
            em.remove(u);
            em.getTransaction().commit();

            btnBuscar.doClick();

            JOptionPane.showMessageDialog(this, "Unidade excluida com sucesso!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        List <Unidade> unidades = em
        .createQuery("SELECT u FROM Unidade u")
        .getResultList();

        DefaultTableModel model = (DefaultTableModel) tblUnidade.getModel();

        model.setRowCount(0);
        for(Unidade u : unidades) {
            model.addRow(
                new Object[] {
                    u.getId(),
                    u.getNome(),
                    u.getCep(),
                    u.getEndereco(),
                    u.getNumero(),
                    u.getCidade(),
                    u.getUf(),
                    u.getTelefone(),
                    u.getEmail()

                }
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUnidadeMouseClicked
        // TODO add your handling code here:
//        int row = tblUnidade.getSelectedRow();
//
//        if(row > -1 && evt.getClickCount()==2){
//            Integer id = (Integer) tblUnidade.getModel().getValueAt(row, 0);
//
//            Unidade u = em.find(Unidade.class, id);
//            this.idUnidade = u.getId();
//            txtNome.setText(u.getNome());
//            txtCep.setText(u.getCep());
//            txtEndereco.setText(u.getEndereco());
//            txtNumero.setText(u.getNumero());
//            txtCidade.setText(u.getCidade());
//            txtUf.setText(u.getUf());
//            txtTelefone.setText(u.getTelefone());

    }//GEN-LAST:event_tblUnidadeMouseClicked

    private void BtnCadastroUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroUnidadeActionPerformed
        TelaCadastroUnidade tela = new TelaCadastroUnidade(new javax.swing.JFrame(), true);
        
        tela.setVisible(true);
        
    }//GEN-LAST:event_BtnCadastroUnidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaTabelaUnidade dialog = new TelaTabelaUnidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastroUnidade;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnidade;
    // End of variables declaration//GEN-END:variables
}
