/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.centralleitos.ui;
/*
import br.newtonpaiva.centralleitos.modelos.Usuario;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
/*

/**
 *
 * @author oXCToo
 */

/*public class TelaLogin extends javax.swing.JFrame {
    
    private Integer numTentativas = 0;
    
        // Codigo para manipular o banco de dados. 
    private final EntityManager em;
    
    public boolean autenticado = false;


    public TelaLogin() {
        initComponents();
        
        Usuario u;
        
        em = Persistence.createEntityManagerFactory("CentralLeitosPU").createEntityManager();
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        numTentativas ++;
        
        Usuario usuario;
        
        try {
            usuario = (Usuario) em.createQuery("SELECT u FROM Usuario u WHERE u.login = :login")
                                  .setParameter("login", txtLogin.getText())
                                  .getSingleResult();
        } catch(NoResultException e) {
            usuario = null;
        }
        
        if(usuario != null && usuario.getSenha().equals(txtSenha.getText())){
            new MenuInicial().setVisible(true);
            this.setVisible(false);
            
            autenticado = true;
            
        }
            
        else if(numTentativas >= 3) {
            JOptionPane.showMessageDialog(this, "Máximo de tentativas atingidas, o sistema será finalizado!");
            autenticado = false;
            System.exit(0);
        } 
        else {
            JOptionPane.showMessageDialog(this, "Usuário ou Senha incorretos, tente novamente!");
            txtSenha.requestFocus(); 
        }
    }//GEN-LAST:event_jButton1MouseClicked
*/
    /**
     * @param args the command line arguments
     */
/* 
public static void main(String args[]) { */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
*/
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
/*}
*/