/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.centralleitos.ui;


import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import br.newtonpaiva.centralleitos.modelos.Endereco;
import br.newtonpaiva.centralleitos.modelos.Leito;
import br.newtonpaiva.centralleitos.modelos.Paciente;
import br.newtonpaiva.centralleitos.modelos.Sexo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author SilasL
 */
public class TelaCrudPaciente extends javax.swing.JDialog {
    private final EntityManager em;
    //private Integer idLeito;
    private Integer idPaciente;
    /**
     * Creates new form TelaCrudUsuario
     */
    public TelaCrudPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        em = Persistence.createEntityManagerFactory("CentralLeitosPU").createEntityManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        lblNameResp = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumCasa = new javax.swing.JLabel();
        txtNumCasa = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNameResp = new javax.swing.JTextField();
        lblParentesco = new javax.swing.JLabel();
        txtParentesco = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox();
        lblTelefone = new javax.swing.JLabel();
        lblEnfermaria = new javax.swing.JLabel();
        txtEnfermaria = new javax.swing.JTextField();
        lblClinica = new javax.swing.JLabel();
        txtClinica = new javax.swing.JTextField();
        lblLeito = new javax.swing.JLabel();
        txtLeito = new javax.swing.JTextField();
        lblTelClinica = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        lblCrm = new javax.swing.JLabel();
        txtCrm = new javax.swing.JTextField();
        lblEnfermeiro = new javax.swing.JLabel();
        txtEnfermeiro = new javax.swing.JTextField();
        lblCoren = new javax.swing.JLabel();
        txtCoren = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblDtaAdimissao = new javax.swing.JLabel();
        lblOncologico = new javax.swing.JLabel();
        cbxOncologico = new javax.swing.JComboBox();
        lblMotivoInternacao = new javax.swing.JLabel();
        txtMotivoInternacao = new javax.swing.JTextField();
        lblDiagnostico = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        lblCid = new javax.swing.JLabel();
        txtCid = new javax.swing.JTextField();
        lblDiagnosticoSec = new javax.swing.JLabel();
        txtDiagnosticoSec = new javax.swing.JTextField();
        lblIntercorrencias = new javax.swing.JLabel();
        txtIntercorrencias = new javax.swing.JTextField();
        lblAlergia = new javax.swing.JLabel();
        cbxAlergia = new javax.swing.JComboBox();
        lblFebre = new javax.swing.JLabel();
        cbxFebre = new javax.swing.JComboBox();
        lblInternadoUti = new javax.swing.JLabel();
        cbxInternadoUti = new javax.swing.JComboBox();
        lblIsolamento = new javax.swing.JLabel();
        cbxIsolamento = new javax.swing.JComboBox();
        lblPatogeno = new javax.swing.JLabel();
        txtPatogeno = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        txtDescAlergia = new javax.swing.JTextField();
        lblDescAlergia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxTipoSan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox();
        txtDtaNascimento = new javax.swing.JFormattedTextField();
        txtDtaAdimissao = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtTelClinica = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();

        jPasswordField1.setText("jPasswordField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setText("Nome:");

        lblNascimento.setText("Data de nascismento:");

        lblNameResp.setText("Nome do responsável:");

        lblEndereco.setText("Endereço:");

        txtEndereco.setEditable(false);

        lblNumCasa.setText("Número:");

        lblBairro.setText("Bairro:");

        txtBairro.setEditable(false);

        lblParentesco.setText("Grau de Parentesco:");

        lblSexo.setText("Sexo:");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino", "Outro" }));

        lblTelefone.setText("Telefone:");

        lblEnfermaria.setText("Dados da enfermaria:");

        lblClinica.setText("Clínica:");

        lblLeito.setText("Leito:");

        lblTelClinica.setText("Telefone:");

        lblMedico.setText("Nome do médico:");

        lblCrm.setText("CRM:");

        lblEnfermeiro.setText("Nome do enfermeiro:");

        lblCoren.setText("Coren:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblDtaAdimissao.setText("Data de admissão:");

        lblOncologico.setText("Paciente oncológico paliático:");

        cbxOncologico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Sim", "Não" }));

        lblMotivoInternacao.setText("Motivo da internação:");

        lblDiagnostico.setText("Diagnóstico principal:");

        lblCid.setText("CID:");

        lblDiagnosticoSec.setText("Diagnóstico secundario:");

        lblIntercorrencias.setText("Intercorrências durante Internação:");

        lblAlergia.setText("Alergia:");

        cbxAlergia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Sim", "Não" }));

        lblFebre.setText("Febre nas últimas 48 horas:");

        cbxFebre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Sim", "Não" }));

        lblInternadoUti.setText("Esteve internado em UTI:");

        cbxInternadoUti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Sim", "Não" }));

        lblIsolamento.setText("Esteve em isolamento:");

        cbxIsolamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Sim", "Não" }));

        lblPatogeno.setText("Se sim, qual o patogeno:");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblDescAlergia.setText("Se sim, qual:");

        jLabel1.setText("Altura:");

        jLabel2.setText("Peso:");

        jLabel3.setText("Tipo sanguíneo:");

        cbxTipoSan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel4.setText("CPF:");

        jLabel5.setText("Cidade:");

        txtCidade.setEditable(false);

        jLabel6.setText("UF:");

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            txtDtaNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtaNascimento.setToolTipText("Informe a Data de Nascimento");

        try {
            txtDtaAdimissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtaAdimissao.setToolTipText("Informe a Data de Nascimento");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setToolTipText("Informe o CPF");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setToolTipText("Incluir o telefone do Médico");

        try {
            txtTelClinica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelClinica.setToolTipText("Incluir o telefone do Médico");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCepFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMedico)
                        .addGap(29, 29, 29)
                        .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnfermeiro)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDtaAdimissao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCrm)
                        .addGap(33, 33, 33)
                        .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtClinica)
                        .addGap(4, 4, 4)
                        .addComponent(lblTelClinica)
                        .addGap(2, 2, 2)
                        .addComponent(txtTelClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLeito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCoren)
                        .addGap(26, 26, 26)
                        .addComponent(txtCoren, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtMotivoInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblIntercorrencias))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtIntercorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAlergia)
                        .addGap(4, 4, 4)
                        .addComponent(cbxAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblDescAlergia)
                        .addGap(4, 4, 4)
                        .addComponent(txtDescAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFebre)
                        .addGap(10, 10, 10)
                        .addComponent(cbxFebre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblInternadoUti)
                        .addGap(10, 10, 10)
                        .addComponent(cbxInternadoUti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(cbxTipoSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblIsolamento)
                        .addGap(10, 10, 10)
                        .addComponent(cbxIsolamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblPatogeno)
                        .addGap(10, 10, 10)
                        .addComponent(txtPatogeno, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(823, 823, 823)
                        .addComponent(btnLimpar)
                        .addGap(6, 6, 6)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNameResp)
                        .addGap(4, 4, 4)
                        .addComponent(txtNameResp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblParentesco)
                        .addGap(4, 4, 4)
                        .addComponent(txtParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblTelefone))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)
                        .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumCasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnfermaria)
                                .addGap(7, 7, 7)
                                .addComponent(txtEnfermaria, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMotivoInternacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDiagnostico)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiagnosticoSec)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDiagnosticoSec)
                            .addComponent(txtDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCid)
                        .addGap(4, 4, 4)
                        .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDtaAdimissao)
                        .addGap(195, 195, 195)
                        .addComponent(lblOncologico)
                        .addGap(10, 10, 10)
                        .addComponent(cbxOncologico, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblName)
                        .addGap(4, 4, 4)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblNascimento)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDtaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lblSexo)
                                .addGap(4, 4, 4)
                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNascimento)
                        .addComponent(txtDtaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSexo)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameResp)
                            .addComponent(lblParentesco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTelefone)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBairro)
                        .addComponent(jLabel5)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEndereco)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumCasa)
                            .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnfermaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLeito)
                        .addComponent(txtLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelClinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnfermaria)
                            .addComponent(lblClinica)
                            .addComponent(lblTelClinica))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedico)
                            .addComponent(lblCrm))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnfermeiro)
                            .addComponent(lblCoren))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxOncologico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDtaAdimissao)
                                .addComponent(txtDtaAdimissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOncologico))))
                .addGap(6, 6, 6)
                .addComponent(lblMotivoInternacao)
                .addGap(6, 6, 6)
                .addComponent(txtMotivoInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiagnostico)
                            .addComponent(lblCid))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDiagnosticoSec))
                    .addComponent(txtDiagnosticoSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblIntercorrencias)
                .addGap(6, 6, 6)
                .addComponent(txtIntercorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlergia)
                            .addComponent(lblDescAlergia))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxFebre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxInternadoUti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFebre)
                            .addComponent(lblInternadoUti)
                            .addComponent(jLabel3))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxIsolamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatogeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIsolamento)
                            .addComponent(lblPatogeno))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxSexo, jLabel1, jLabel2, jLabel4, lblName, lblNascimento, lblSexo, txtAltura, txtCpf, txtDtaNascimento, txtName, txtPeso});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        em.getTransaction().begin();
        Paciente p;
        
        String message = "";
        if(this.idPaciente == null){
            p = new Paciente();     
            message = "cadastrado";
            em.persist(p);  
        } else {
            p = em.find(Paciente.class, idPaciente);
            message = "editado";
            em.merge(p);
        }
        
        p.setNome(txtName.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
	Calendar calN = Calendar.getInstance();//nascimento
        Calendar calA = Calendar.getInstance();//admissao
        try {
            calN.setTime(sdf.parse(txtDtaNascimento.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaCrudPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setDataNascimento(calN);
        if(cbxSexo.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para o sexo do paciente.");
            return;
        } else {
            p.setSexo(cbxSexo.getSelectedItem().toString());
        }
        if(cbxTipoSan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para o tipo sanguíneo do paciente.");
            return;
        } else {
            p.setTipoSanguineo(cbxTipoSan.getSelectedItem().toString());
        }
        p.setNomeResp(txtNameResp.getText());
        p.setGrauParentesco(txtParentesco.getText());
        p.setTelefone(txtTelefone.getText());
        p.setDadosEnfermaria(txtEnfermaria.getText());
        p.setClinica(txtClinica.getText());
        p.setTelefoneClinica(txtTelClinica.getText());
        //l.setId();
        p.setNomeMedico(txtMedico.getText());
        p.setNomeEnfermeiro(txtEnfermeiro.getText());
        p.setCoren(txtCoren.getText());
        
        try {
            calA.setTime(sdf.parse(txtDtaAdimissao.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaCrudPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setDataAdimissao(calA);
        
        if(cbxOncologico.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para o paciente oncológico paliatico.");
            return;
        } else {
            p.setPacienteOncologico(cbxOncologico.getSelectedItem().toString());
        }
        p.setMotivoInternacao(txtMotivoInternacao.getText());
        p.setDiagnosticoPrincipal(txtDiagnostico.getText());
        p.setCid(txtCid.getText());
        p.setDiagnosticoSecundario(txtDiagnosticoSec.getText());
        p.setIntercorrencias(txtIntercorrencias.getText());
        if(cbxAlergia.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para alergia.");
            return;
        } else {
            p.setAlergia(cbxAlergia.getSelectedItem().toString());
        }
        p.setDescAlergia(txtDescAlergia.getText());
        if(cbxFebre.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para febre.");
            return;
        } else {
            p.setFebre(cbxFebre.getSelectedItem().toString());
        }
        if(cbxInternadoUti.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para Internado em UTI.");
            return;
        } else {
            p.setInternadoUti(cbxInternadoUti.getSelectedItem().toString());
        }
        if(cbxIsolamento.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(this, "Selecione uma opção válida para esteve em isolamento.");
            return;
        } else {
            p.setIsolamento(cbxIsolamento.getSelectedItem().toString());
        }
        p.setPatogeno(txtPatogeno.getText());
        p.setAltura(Double.parseDouble(txtAltura.getText()));
        p.setPeso(Double.parseDouble(txtPeso.getText()));
        p.setCrm(txtCrm.getText());
        if (txtCpf.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "O CPF é obrigatório","AVISO!",JOptionPane.WARNING_MESSAGE);
            txtCpf.requestFocus();
             return;
        }else
            p.setCpf(txtCpf.getText());
        
        if(txtEndereco.getText().trim().isEmpty())
            p.setEndereco(null);
        else{
            p.setEndereco(txtEndereco.getText());
        }
        if(txtCep.getText().trim().isEmpty())
            p.setCep(null);
        else{
            p.setCep(txtCep.getText());
        }
        if(txtBairro.getText().trim().isEmpty())
            p.setBairro(null);
        else{
            p.setBairro(txtBairro.getText());
        }        
        if(cbxUF.getSelectedIndex()==0)
            p.setUF(null);
        else{
            p.setUF(Integer.toString(cbxUF.getSelectedIndex()));
        }
        if(txtNumCasa.getText().trim().isEmpty())
            p.setNumero(null);
        else{
            p.setNumero(Integer.parseInt(txtNumCasa.getText()));
        }
        if(txtCidade.getText().trim().isEmpty()){
            p.setCidade(null);
        }else{
            p.setCidade(txtCidade.getText());
        }
        em.persist(p);
        em.getTransaction().commit();
        em.close();
        
        JOptionPane.showMessageDialog(this, "Paciente "+ message +" com sucesso!");
        btnLimpar.doClick();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.idPaciente = null;
        txtName.setText("");
        txtNameResp.setText("");
        txtParentesco.setText("");
        txtCep.setText("");
        txtBairro.setText("");
        txtEndereco.setText("");
        cbxUF.setSelectedItem(" ");
        txtCidade.setText("");
        txtClinica.setText("");
        txtEnfermeiro.setText("");
        txtCoren.setText("");
        txtDtaNascimento.setText("");
        txtEnfermaria.setText("");
        cbxSexo.setSelectedItem("Selecione...");
        txtNumCasa.setText("");
        txtLeito.setText("");
        txtMedico.setText("");
        txtCrm.setText("");
        txtDtaAdimissao.setText("");
        cbxOncologico.setSelectedItem("Selecione...");
        txtMotivoInternacao.setText("");
        txtDiagnostico.setText("");
        txtDiagnosticoSec.setText("");
        txtCid.setText("");
        txtIntercorrencias.setText("");
        txtDescAlergia.setText("");
        cbxAlergia.setSelectedItem("Selecione...");
        cbxFebre.setSelectedItem("Selecione...");
        cbxInternadoUti.setSelectedItem("Selecione...");
        cbxIsolamento.setSelectedItem("Selecione...");
        txtPatogeno.setText("");
        txtTelClinica.setText("");
        txtTelefone.setText("");
        txtPeso.setText("");
        txtAltura.setText("");
        cbxTipoSan.setSelectedItem("Selecione...");
        txtCpf.setText("");
        
        txtName.requestFocus();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCepFocusLost
        ViaCEP viaCep = new ViaCEP();
        
        String cp = txtCep.getText().replace("-","");
        
        try {
            viaCep.buscar(cp);
            txtEndereco.setText(viaCep.getLogradouro());
            txtBairro.setText(viaCep.getBairro());
            cbxUF.setSelectedItem(viaCep.getUf());
            txtCidade.setText(viaCep.getLocalidade());
        } catch (ViaCEPException ex) {
            JOptionPane.showMessageDialog(null, ex);//,JOptionPane.WARNING_MESSAGE);
        }//"Falha ao Buscar o CEP, preencha manualmente","AVISO!"
    }//GEN-LAST:event_txtCepFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCrudPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCrudPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCrudPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCrudPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCrudPaciente dialog = new TelaCrudPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxAlergia;
    private javax.swing.JComboBox cbxFebre;
    private javax.swing.JComboBox cbxInternadoUti;
    private javax.swing.JComboBox cbxIsolamento;
    private javax.swing.JComboBox cbxOncologico;
    private javax.swing.JComboBox cbxSexo;
    private javax.swing.JComboBox cbxTipoSan;
    private javax.swing.JComboBox cbxUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlergia;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCid;
    private javax.swing.JLabel lblClinica;
    private javax.swing.JLabel lblCoren;
    private javax.swing.JLabel lblCrm;
    private javax.swing.JLabel lblDescAlergia;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblDiagnosticoSec;
    private javax.swing.JLabel lblDtaAdimissao;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEnfermaria;
    private javax.swing.JLabel lblEnfermeiro;
    private javax.swing.JLabel lblFebre;
    private javax.swing.JLabel lblIntercorrencias;
    private javax.swing.JLabel lblInternadoUti;
    private javax.swing.JLabel lblIsolamento;
    private javax.swing.JLabel lblLeito;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblMotivoInternacao;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameResp;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNumCasa;
    private javax.swing.JLabel lblOncologico;
    private javax.swing.JLabel lblParentesco;
    private javax.swing.JLabel lblPatogeno;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelClinica;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtClinica;
    private javax.swing.JTextField txtCoren;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtCrm;
    private javax.swing.JTextField txtDescAlergia;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtDiagnosticoSec;
    private javax.swing.JFormattedTextField txtDtaAdimissao;
    private javax.swing.JFormattedTextField txtDtaNascimento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnfermaria;
    private javax.swing.JTextField txtEnfermeiro;
    private javax.swing.JTextField txtIntercorrencias;
    private javax.swing.JTextField txtLeito;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtMotivoInternacao;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameResp;
    private javax.swing.JTextField txtNumCasa;
    private javax.swing.JTextField txtParentesco;
    private javax.swing.JTextField txtPatogeno;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JFormattedTextField txtTelClinica;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
